channels:
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - azureml-core==1.21.0.post1
  - azureml-defaults==1.21.0
  - azureml-telemetry==1.21.0
  - azureml-train-restclients-hyperdrive==1.21.0
  - azureml-train-core==1.21.0
  - tensorflow==2.2.0
  - horovod==0.19.5
name: azureml_ff6c5e7cf1cbe3e8ae7acc2938177052
